name: Projects Matrix PoC

on:
  workflow_dispatch:
    inputs:
      matrix_list:
        description: "List of project+env combinations as JSON"
        required: true
        default: >
          [
            {"project": "1000-5", "env": "dev"},
            {"project": "1000-5", "env": "mlops"},
            {"project": "1000-5", "env": "prd"},
            {"project": "1000-6", "env": "dev"},
            {"project": "1000-6", "env": "prd"}
          ]
      exclude_list:
        description: "Array of project:env combos to exclude"
        required: false
        default: '["1000-5:mlops","1000-6:dev"]'

jobs:
  project-env-matrix:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        include: ${{ fromJSON(github.event.inputs.matrix_list) }}

    steps:
      - name: Display project and environment
        run: |
          EXCLUDES=$(echo '${{ github.event.inputs.exclude_list }}' | jq -r '.[]')
          KEY="${{ matrix.project }}:${{ matrix.env }}"

          for ex in $EXCLUDES; do
            if [ "$KEY" = "$ex" ]; then
              echo "Skipping $KEY"
              exit 0
            fi
          done

          echo "Processing $KEY"
          sleep 10
          echo "Project: ${{ matrix.project }}"
          echo "Environment: ${{ matrix.env }}"
