name: Projects Matrix PoC

on:
  workflow_dispatch:
    inputs:
      projects:
        description: "Projects to deploy (comma-separated, e.g., 1000-5,1000-6,1000-7)"
        required: false
        default: "1000-5,1000-6,1000-7,1000-8,1000-9"
      
      environments:
        description: "Environments to deploy (comma-separated, e.g., dev,mlops,prd)"
        required: false
        default: "dev,mlops,prd"
      
      exclude:
        description: "Exclude combinations (comma-separated, e.g., 1000-5:mlops,1000-6:dev)"
        required: false
        default: "1000-5:mlops,1000-6:dev"

jobs:
  # 1000-5:dev
  plan_1000-5_dev:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.inputs.projects, '1000-5') &&
      contains(github.event.inputs.environments, 'dev') &&
      !contains(github.event.inputs.exclude, '1000-5:dev')
    steps:
      - name: Plan 1000-5:dev
        run: echo "Plan 1000-5:dev"

  apply_1000-5_dev:
    runs-on: ubuntu-latest
    needs: plan_1000-5_dev
    if: |
      contains(github.event.inputs.projects, '1000-5') &&
      contains(github.event.inputs.environments, 'dev') &&
      !contains(github.event.inputs.exclude, '1000-5:dev')
    environment: approve-1000-5-dev
    steps:
      - name: Apply 1000-5:dev
        run: echo "Apply 1000-5:dev"

  # 1000-5:mlops
  plan_1000-5_mlops:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.inputs.projects, '1000-5') &&
      contains(github.event.inputs.environments, 'mlops') &&
      !contains(github.event.inputs.exclude, '1000-5:mlops')
    steps:
      - name: Plan 1000-5:mlops
        run: echo "Plan 1000-5:mlops"

  apply_1000-5_mlops:
    runs-on: ubuntu-latest
    needs: plan_1000-5_mlops
    if: |
      contains(github.event.inputs.projects, '1000-5') &&
      contains(github.event.inputs.environments, 'mlops') &&
      !contains(github.event.inputs.exclude, '1000-5:mlops')
    environment: approve-1000-5-mlops
    steps:
      - name: Apply 1000-5:mlops
        run: echo "Apply 1000-5:mlops"

  # 1000-5:prd
  plan_1000-5_prd:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.inputs.projects, '1000-5') &&
      contains(github.event.inputs.environments, 'prd') &&
      !contains(github.event.inputs.exclude, '1000-5:prd')
    steps:
      - name: Plan 1000-5:prd
        run: |
          echo "Plan 1000-5:prd"
          exit 1  # Este plan falla intencionalmente

  apply_1000-5_prd:
    runs-on: ubuntu-latest
    needs: plan_1000-5_prd
    if: |
      contains(github.event.inputs.projects, '1000-5') &&
      contains(github.event.inputs.environments, 'prd') &&
      !contains(github.event.inputs.exclude, '1000-5:prd')
    environment: approve-1000-5-prd
    steps:
      - name: Apply 1000-5:prd
        run: echo "Apply 1000-5:prd"

  # 1000-6:dev
  plan_1000-6_dev:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.inputs.projects, '1000-6') &&
      contains(github.event.inputs.environments, 'dev') &&
      !contains(github.event.inputs.exclude, '1000-6:dev')
    steps:
      - name: Plan 1000-6:dev
        run: echo "Plan 1000-6:dev"

  apply_1000-6_dev:
    runs-on: ubuntu-latest
    needs: plan_1000-6_dev
    if: |
      contains(github.event.inputs.projects, '1000-6') &&
      contains(github.event.inputs.environments, 'dev') &&
      !contains(github.event.inputs.exclude, '1000-6:dev')
    environment: approve-1000-6-dev
    steps:
      - name: Apply 1000-6:dev
        run: echo "Apply 1000-6:dev"

  # 1000-6:mlops
  plan_1000-6_mlops:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.inputs.projects, '1000-6') &&
      contains(github.event.inputs.environments, 'mlops') &&
      !contains(github.event.inputs.exclude, '1000-6:mlops')
    steps:
      - name: Plan 1000-6:mlops
        run: echo "Plan 1000-6:mlops"

  apply_1000-6_mlops:
    runs-on: ubuntu-latest
    needs: plan_1000-6_mlops
    if: |
      contains(github.event.inputs.projects, '1000-6') &&
      contains(github.event.inputs.environments, 'mlops') &&
      !contains(github.event.inputs.exclude, '1000-6:mlops')
    environment: approve-1000-6-mlops
    steps:
      - name: Apply 1000-6:mlops
        run: echo "Apply 1000-6:mlops"

  # 1000-6:prd
  plan_1000-6_prd:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.inputs.projects, '1000-6') &&
      contains(github.event.inputs.environments, 'prd') &&
      !contains(github.event.inputs.exclude, '1000-6:prd')
    steps:
      - name: Plan 1000-6:prd
        run: echo "Plan 1000-6:prd"

  apply_1000-6_prd:
    runs-on: ubuntu-latest
    needs: plan_1000-6_prd
    if: |
      contains(github.event.inputs.projects, '1000-6') &&
      contains(github.event.inputs.environments, 'prd') &&
      !contains(github.event.inputs.exclude, '1000-6:prd')
    environment: approve-1000-6-prd
    steps:
      - name: Apply 1000-6:prd
        run: echo "Apply 1000-6:prd"

  # 1000-7:dev
  plan_1000-7_dev:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.inputs.projects, '1000-7') &&
      contains(github.event.inputs.environments, 'dev') &&
      !contains(github.event.inputs.exclude, '1000-7:dev')
    steps:
      - name: Plan 1000-7:dev
        run: echo "Plan 1000-7:dev"

  apply_1000-7_dev:
    runs-on: ubuntu-latest
    needs: plan_1000-7_dev
    if: |
      contains(github.event.inputs.projects, '1000-7') &&
      contains(github.event.inputs.environments, 'dev') &&
      !contains(github.event.inputs.exclude, '1000-7:dev')
    environment: approve-1000-7-dev
    steps:
      - name: Apply 1000-7:dev
        run: echo "Apply 1000-7:dev"

  # 1000-7:mlops
  plan_1000-7_mlops:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.inputs.projects, '1000-7') &&
      contains(github.event.inputs.environments, 'mlops') &&
      !contains(github.event.inputs.exclude, '1000-7:mlops')
    steps:
      - name: Plan 1000-7:mlops
        run: echo "Plan 1000-7:mlops"

  apply_1000-7_mlops:
    runs-on: ubuntu-latest
    needs: plan_1000-7_mlops
    if: |
      contains(github.event.inputs.projects, '1000-7') &&
      contains(github.event.inputs.environments, 'mlops') &&
      !contains(github.event.inputs.exclude, '1000-7:mlops')
    environment: approve-1000-7-mlops
    steps:
      - name: Apply 1000-7:mlops
        run: echo "Apply 1000-7:mlops"

  # 1000-7:prd
  plan_1000-7_prd:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.inputs.projects, '1000-7') &&
      contains(github.event.inputs.environments, 'prd') &&
      !contains(github.event.inputs.exclude, '1000-7:prd')
    steps:
      - name: Plan 1000-7:prd
        run: echo "Plan 1000-7:prd"

  apply_1000-7_prd:
    runs-on: ubuntu-latest
    needs: plan_1000-7_prd
    if: |
      contains(github.event.inputs.projects, '1000-7') &&
      contains(github.event.inputs.environments, 'prd') &&
      !contains(github.event.inputs.exclude, '1000-7:prd')
    environment: approve-1000-7-prd
    steps:
      - name: Apply 1000-7:prd
        run: echo "Apply 1000-7:prd"

  # 1000-8:dev
  plan_1000-8_dev:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.inputs.projects, '1000-8') &&
      contains(github.event.inputs.environments, 'dev') &&
      !contains(github.event.inputs.exclude, '1000-8:dev')
    steps:
      - name: Plan 1000-8:dev
        run: echo "Plan 1000-8:dev"

  apply_1000-8_dev:
    runs-on: ubuntu-latest
    needs: plan_1000-8_dev
    if: |
      contains(github.event.inputs.projects, '1000-8') &&
      contains(github.event.inputs.environments, 'dev') &&
      !contains(github.event.inputs.exclude, '1000-8:dev')
    environment: approve-1000-8-dev
    steps:
      - name: Apply 1000-8:dev
        run: echo "Apply 1000-8:dev"

  # 1000-8:mlops
  plan_1000-8_mlops:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.inputs.projects, '1000-8') &&
      contains(github.event.inputs.environments, 'mlops') &&
      !contains(github.event.inputs.exclude, '1000-8:mlops')
    steps:
      - name: Plan 1000-8:mlops
        run: echo "Plan 1000-8:mlops"

  apply_1000-8_mlops:
    runs-on: ubuntu-latest
    needs: plan_1000-8_mlops
    if: |
      contains(github.event.inputs.projects, '1000-8') &&
      contains(github.event.inputs.environments, 'mlops') &&
      !contains(github.event.inputs.exclude, '1000-8:mlops')
    environment: approve-1000-8-mlops
    steps:
      - name: Apply 1000-8:mlops
        run: echo "Apply 1000-8:mlops"

  # 1000-8:prd
  plan_1000-8_prd:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.inputs.projects, '1000-8') &&
      contains(github.event.inputs.environments, 'prd') &&
      !contains(github.event.inputs.exclude, '1000-8:prd')
    steps:
      - name: Plan 1000-8:prd
        run: echo "Plan 1000-8:prd"

  apply_1000-8_prd:
    runs-on: ubuntu-latest
    needs: plan_1000-8_prd
    if: |
      contains(github.event.inputs.projects, '1000-8') &&
      contains(github.event.inputs.environments, 'prd') &&
      !contains(github.event.inputs.exclude, '1000-8:prd')
    environment: approve-1000-8-prd
    steps:
      - name: Apply 1000-8:prd
        run: echo "Apply 1000-8:prd"

  # 1000-9:dev
  plan_1000-9_dev:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.inputs.projects, '1000-9') &&
      contains(github.event.inputs.environments, 'dev') &&
      !contains(github.event.inputs.exclude, '1000-9:dev')
    steps:
      - name: Plan 1000-9:dev
        run: echo "Plan 1000-9:dev"

  apply_1000-9_dev:
    runs-on: ubuntu-latest
    needs: plan_1000-9_dev
    if: |
      contains(github.event.inputs.projects, '1000-9') &&
      contains(github.event.inputs.environments, 'dev') &&
      !contains(github.event.inputs.exclude, '1000-9:dev')
    environment: approve-1000-9-dev
    steps:
      - name: Apply 1000-9:dev
        run: echo "Apply 1000-9:dev"

  # 1000-9:mlops
  plan_1000-9_mlops:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.inputs.projects, '1000-9') &&
      contains(github.event.inputs.environments, 'mlops') &&
      !contains(github.event.inputs.exclude, '1000-9:mlops')
    steps:
      - name: Plan 1000-9:mlops
        run: echo "Plan 1000-9:mlops"

  apply_1000-9_mlops:
    runs-on: ubuntu-latest
    needs: plan_1000-9_mlops
    if: |
      contains(github.event.inputs.projects, '1000-9') &&
      contains(github.event.inputs.environments, 'mlops') &&
      !contains(github.event.inputs.exclude, '1000-9:mlops')
    environment: approve-1000-9-mlops
    steps:
      - name: Apply 1000-9:mlops
        run: echo "Apply 1000-9:mlops"

  # 1000-9:prd
  plan_1000-9_prd:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.inputs.projects, '1000-9') &&
      contains(github.event.inputs.environments, 'prd') &&
      !contains(github.event.inputs.exclude, '1000-9:prd')
    steps:
      - name: Plan 1000-9:prd
        run: echo "Plan 1000-9:prd"

  apply_1000-9_prd:
    runs-on: ubuntu-latest
    needs: plan_1000-9_prd
    if: |
      contains(github.event.inputs.projects, '1000-9') &&
      contains(github.event.inputs.environments, 'prd') &&
      !contains(github.event.inputs.exclude, '1000-9:prd')
    environment: approve-1000-9-prd
    steps:
      - name: Apply 1000-9:prd
        run: echo "Apply 1000-9:prd"
