name: Projects Matrix PoC

on:
  workflow_dispatch:
    inputs:
      matrix_list:
        description: "List of combinations project+env+region as JSON"
        required: true
        default: >        
          [
            {"project": "1000-5", "env": "dev", "region": "eu-west-1"},
            {"project": "1000-5", "env": "mlops", "region": "eu-west-1"},
            {"project": "1000-5", "env": "prd", "region": "eu-west-1"}
          ]
      exclude_list:
        description: "Lista de combos project:env a excluir, separados por coma"
        required: false
        default: "1000-5:mlops"

jobs:
  project-env-matrix:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        include: ${{ fromJSON(github.event.inputs.matrix_list) }}

    steps:
      - name: Show project and environment
        run: |
          EXCLUDES="${{ github.event.inputs.exclude_list }}"
          KEY="${{ matrix.project }}:${{ matrix.env }}"

          if echo "$EXCLUDES" | grep -q "$KEY"; then
            echo "Skipping $KEY"
            exit 0
          fi

          sleep 10
          echo "Project: ${{ matrix.project }}"
          echo "Environment: ${{ matrix.env }}"
          echo "Region: ${{ matrix.region }}"
