name: Projects Matrix PoC

on:
  workflow_dispatch:
    inputs:
      matrix_list:
        description: "List of project+env combinations as JSON"
        required: true
        default: >
          [
            {"project": "1000-5", "env": "dev"},
            {"project": "1000-5", "env": "mlops"},
            {"project": "1000-5", "env": "prd"},
            {"project": "1000-6", "env": "dev"},
            {"project": "1000-6", "env": "prd"},
            {"project": "1000-7", "env": "dev"},
            {"project": "1000-7", "env": "mlops"},
            {"project": "1000-7", "env": "prd"},
            {"project": "1000-8", "env": "dev"},
            {"project": "1000-8", "env": "mlops"},
            {"project": "1000-8", "env": "prd"},
            {"project": "1000-9", "env": "dev"},
            {"project": "1000-9", "env": "mlops"},
            {"project": "1000-9", "env": "prd"},
            {"project": "1000-10", "env": "dev"},
            {"project": "1000-10", "env": "mlops"},
            {"project": "1000-10", "env": "prd"},
            {"project": "1000-11", "env": "dev"},
            {"project": "1000-11", "env": "mlops"},
            {"project": "1000-11", "env": "prd"},
            {"project": "1000-12", "env": "dev"},
            {"project": "1000-12", "env": "mlops"},
            {"project": "1000-12", "env": "prd"},
            {"project": "1000-13", "env": "dev"},
            {"project": "1000-13", "env": "mlops"},
            {"project": "1000-13", "env": "prd"},
            {"project": "1000-14", "env": "dev"},
            {"project": "1000-14", "env": "mlops"},
            {"project": "1000-14", "env": "prd"},
            {"project": "1000-15", "env": "dev"},
            {"project": "1000-15", "env": "mlops"},
            {"project": "1000-15", "env": "prd"},
            {"project": "1000-16", "env": "dev"},
            {"project": "1000-16", "env": "mlops"},
            {"project": "1000-16", "env": "prd"},
            {"project": "1000-17", "env": "dev"},
            {"project": "1000-17", "env": "mlops"},
            {"project": "1000-17", "env": "prd"},
            {"project": "1000-18", "env": "dev"},
            {"project": "1000-18", "env": "mlops"},
            {"project": "1000-18", "env": "prd"},
            {"project": "1000-19", "env": "dev"},
            {"project": "1000-19", "env": "mlops"},
            {"project": "1000-19", "env": "prd"},
            {"project": "1000-20", "env": "dev"},
            {"project": "1000-20", "env": "mlops"},
            {"project": "1000-20", "env": "prd"}
          ]

      exclude_list:
        description: "Array of project:env combos to exclude"
        required: false
        default: '["1000-5:mlops","1000-6:dev"]'

jobs:
  plan_1000_5_dev:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Plan 1000-5:dev"

  apply_1000_5_dev:
    runs-on: ubuntu-latest
    needs: plan_1000_5_dev
    environment: approve-1000-5-dev
    steps:
      - run: echo "Apply 1000-5:dev"

  plan_1000_5_prd:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Plan 1000-5:prd"
          exit 1  # solo este plan falla

  apply_1000_5_prd:
    runs-on: ubuntu-latest
    needs: plan_1000_5_prd
    environment: approve-1000-5-prd
    steps:
      - run: echo "Apply 1000-5:prd"
