name: Projects Matrix PoC

on:
  workflow_dispatch:
    inputs:
      matrix_list:
        description: "List of project+env combinations as JSON"
        required: true
        default: >
          [
            {"project": "1000-5", "env": "dev"},
            {"project": "1000-5", "env": "mlops"},
            {"project": "1000-5", "env": "prd"},
            {"project": "1000-6", "env": "dev"},
            {"project": "1000-6", "env": "prd"}
          ]
      exclude_list:
        description: "Array of project:env combos to exclude"
        required: false
        default: '["1000-5:mlops","1000-6:dev"]'

jobs:
  # Genera un job plan para cada combo
  plan:
    name: plan-${{ matrix.project }}-${{ matrix.env }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJSON(github.event.inputs.matrix_list) }}
    steps:
      - name: Check if excluded
        id: check_exclude
        run: |
          EXCLUDES=$(echo '${{ github.event.inputs.exclude_list }}' | jq -r '.[]')
          KEY="${{ matrix.project }}:${{ matrix.env }}"
          SKIP=false
          for ex in $EXCLUDES; do
            if [ "$KEY" = "$ex" ]; then
              echo "This combo is excluded: $KEY"
              SKIP=true
              break
            fi
          done
          echo "skip=$SKIP" >> $GITHUB_OUTPUT

      - name: Plan step
        if: ${{ steps.check_exclude.outputs.skip != 'true' }}
        run: echo "Planning for ${{ matrix.project }}:${{ matrix.env }}"

  # Genera un job apply para cada combo y depende de su plan equivalente
  apply:
    name: apply-${{ matrix.project }}-${{ matrix.env }}
    needs: [plan] # GitHub entiende que es el plan con el mismo matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJSON(github.event.inputs.matrix_list) }}
    steps:
      - name: Check if excluded
        id: check_exclude
        run: |
          EXCLUDES=$(echo '${{ github.event.inputs.exclude_list }}' | jq -r '.[]')
          KEY="${{ matrix.project }}:${{ matrix.env }}"
          SKIP=false
          for ex in $EXCLUDES; do
            if [ "$KEY" = "$ex" ]; then
              echo "This combo is excluded: $KEY"
              SKIP=true
              break
            fi
          done
          echo "skip=$SKIP" >> $GITHUB_OUTPUT

      - name: Apply step
        if: ${{ steps.check_exclude.outputs.skip != 'true' }}
        run: echo "Applying for ${{ matrix.project }}:${{ matrix.env }}"
