name: Projects Matrix PoC

on:
  workflow_dispatch:
    inputs:
      matrix_list:
        description: "List of project+env combinations as JSON"
        required: true
        default: >
          [
            {"project": "1000-5", "env": "dev"},
            {"project": "1000-5", "env": "mlops"},
            {"project": "1000-5", "env": "prd"},
            {"project": "1000-6", "env": "dev"},
            {"project": "1000-6", "env": "prd"},
            {"project": "1000-7", "env": "dev"},
            {"project": "1000-7", "env": "mlops"},
            {"project": "1000-7", "env": "prd"}
            # ... sigue hasta 1000-56
          ]
      exclude_list:
        description: "Array of project:env combos to exclude"
        required: false
        default: '["1000-5:mlops","1000-6:dev"]'

jobs:
  plan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJSON(github.event.inputs.matrix_list) }}
    outputs:
      plan_key: ${{ steps.set-output.outputs.key }}
    steps:
      - name: Check exclude
        id: check
        run: |
          EXCLUDES=$(echo '${{ github.event.inputs.exclude_list }}' | jq -r '.[]')
          KEY="${{ matrix.project }}:${{ matrix.env }}"
          SKIP=false
          for ex in $EXCLUDES; do
            if [ "$KEY" = "$ex" ]; then
              SKIP=true
              break
            fi
          done
          echo "skip=$SKIP" >> $GITHUB_OUTPUT
          echo "key=$KEY" >> $GITHUB_OUTPUT

      - name: Plan
        if: ${{ steps.check.outputs.skip != 'true' }}
        run: echo "Plan -> ${{ matrix.project }}:${{ matrix.env }}"

# APPLY individual por cada combinación
  apply_1000_5_dev:
    needs: plan
    if: ${{ fromJSON(github.event.inputs.matrix_list)[0].project == '1000-5' && fromJSON(github.event.inputs.matrix_list)[0].env == 'dev' }}
    runs-on: ubuntu-latest
    environment: approve-1000-5-dev
    steps:
      - run: echo "Apply 1000-5:dev"

  apply_1000_5_prd:
    needs: plan
    if: ${{ fromJSON(github.event.inputs.matrix_list)[2].project == '1000-5' && fromJSON(github.event.inputs.matrix_list)[2].env == 'prd' }}
    runs-on: ubuntu-latest
    environment: approve-1000-5-prd
    steps:
      - run: echo "Apply 1000-5:prd"

  apply_1000_6_prd:
    needs: plan
    if: ${{ fromJSON(github.event.inputs.matrix_list)[4].project == '1000-6' && fromJSON(github.event.inputs.matrix_list)[4].env == 'prd' }}
    runs-on: ubuntu-latest
    environment: approve-1000-6-prd
    steps:
      - run: echo "Apply 1000-6:prd"
