name: Projects Matrix PoC

on:
  workflow_dispatch:
    inputs:
      matrix_list:
        description: "List of project+env combinations as JSON"
        required: true
        default: >
          [
            {"project": "1000-5", "env": "dev"},
            {"project": "1000-5", "env": "mlops"},
            {"project": "1000-5", "env": "prd"},
            {"project": "1000-6", "env": "dev"},
            {"project": "1000-6", "env": "prd"},
            {"project": "1000-7", "env": "dev"},
            {"project": "1000-7", "env": "mlops"},
            {"project": "1000-7", "env": "prd"},
            {"project": "1000-8", "env": "dev"},
            {"project": "1000-8", "env": "mlops"},
            {"project": "1000-8", "env": "prd"},
            {"project": "1000-9", "env": "dev"},
            {"project": "1000-9", "env": "mlops"},
            {"project": "1000-9", "env": "prd"},
            {"project": "1000-10", "env": "dev"},
            {"project": "1000-10", "env": "mlops"},
            {"project": "1000-10", "env": "prd"},
            {"project": "1000-11", "env": "dev"},
            {"project": "1000-11", "env": "mlops"},
            {"project": "1000-11", "env": "prd"},
            {"project": "1000-12", "env": "dev"},
            {"project": "1000-12", "env": "mlops"},
            {"project": "1000-12", "env": "prd"},
            {"project": "1000-13", "env": "dev"},
            {"project": "1000-13", "env": "mlops"},
            {"project": "1000-13", "env": "prd"},
            {"project": "1000-14", "env": "dev"},
            {"project": "1000-14", "env": "mlops"},
            {"project": "1000-14", "env": "prd"},
            {"project": "1000-15", "env": "dev"},
            {"project": "1000-15", "env": "mlops"},
            {"project": "1000-15", "env": "prd"},
            {"project": "1000-16", "env": "dev"},
            {"project": "1000-16", "env": "mlops"},
            {"project": "1000-16", "env": "prd"},
            {"project": "1000-17", "env": "dev"},
            {"project": "1000-17", "env": "mlops"},
            {"project": "1000-17", "env": "prd"},
            {"project": "1000-18", "env": "dev"},
            {"project": "1000-18", "env": "mlops"},
            {"project": "1000-18", "env": "prd"},
            {"project": "1000-19", "env": "dev"},
            {"project": "1000-19", "env": "mlops"},
            {"project": "1000-19", "env": "prd"},
            {"project": "1000-20", "env": "dev"},
            {"project": "1000-20", "env": "mlops"},
            {"project": "1000-20", "env": "prd"}
          ]

      exclude_list:
        description: "Array of project:env combos to exclude"
        required: false
        default: '["1000-5:mlops","1000-6:dev"]'

jobs:
  plan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJSON(github.event.inputs.matrix_list) }}
    steps:
      - name: Check exclude
        id: check
        run: |
          EXCLUDES=$(echo '${{ github.event.inputs.exclude_list }}' | jq -r '.[]')
          KEY="${{ matrix.project }}:${{ matrix.env }}"
          SKIP=false
          for ex in $EXCLUDES; do
            if [ "$KEY" = "$ex" ]; then
              SKIP=true
              break
            fi
          done
          echo "skip=$SKIP" >> $GITHUB_OUTPUT

      - name: Plan
        if: ${{ steps.check.outputs.skip != 'true' }}
        run: |
          echo "Plan -> ${{ matrix.project }}:${{ matrix.env }}"
          # falla solo un plan concreto
          if [ "${{ matrix.project }}:${{ matrix.env }}" = "1000-5:prd" ]; then
            echo "Forzando fallo en ${{ matrix.project }}:${{ matrix.env }}"
            exit 1
          fi

